### ISSUE TITLE
Xcode’s “New Build System” builds faulty framework

### ISSUE THREAD

**Issue by pointum** [sparkle-project/Sparkle#1255]
If the framework is built using the Xcode’s New Build System, then Resources folder is missing most .xib files and the update system fails to show corresponding alerts. The New Build System is default in Xcode 10 and opt-in in Xcode 9. Tested with Xcode 9.4.1 and 10 beta 1.

**Steps to reproduce:**

- Download Sparkle sources, e.g. 
https://github.com/sparkle-project/Sparkle/releases/tag/1.19.0

- Open Sparkle.xcodeproj in Xcode 9 or newer
- Select File > Project Settings menu
- Select New Build System from Build System dropdown
- Build Sparkle.framework product
- Inspect contents of Sparkle.framework/Contents/Resources/en.lproj

All .lproj folders should contain .xib files, but only the first one (ar.lproj) does.

This is most likely an Xcode bug, so I filed a bug report with Apple.

**Comment by kornelski** [comment]
Thanks for checking. It's possibly fixed by #1257?

**Comment by pointum** [comment]
I don’t think it’s related. I’ve tested the commit from #1257 and the issue is still there. The project builds with no issues, but localized resources are missing. There’s no test to catch this and no warnings/errors.

**Comment by bewebste** [comment]
I can confirm this happens for me too with Xcode 10 beta 2. I filed a radar on it with Apple https://openradar.appspot.com/radar?id=5027909915901952

**Comment by pointum** [comment]
Seems to be resolved in Xcode 10 beta 3.
