### ISSUE TITLE
Cannot set appcast URL via feedURLStringForUpdater: in SUUpdaterDelegate

### ISSUE THREAD

**Issue by 1024jp** [sparkle-project/Sparkle#704]
My application tells appcast URL to Sparkle using SUUPdaterDelegate's `feedURLStringForUpdater: ` in order to set appcast URL dynamically.

The code worked well at least until Sparkle 1.11.1, however just after I updated Sparkle to 1.13.0, Sparkle began rising an exception with the following error message:

> You must specify the URL of the appcast as the SUFeedURL key in either the Info.plist or the user defaults!

The exception is thrown as SUUpdater is initialized but before I set its delegate.

```objc
SUUpdater *updater = [SUUpdater sharedUpdater];

// >>>>>> Here comes the error.

[updater setDelegate:self];
```

![screen shot 2015-12-28 at 22 54 03](https://cloud.githubusercontent.com/assets/1165044/12019625/fc45a0c8-adb5-11e5-9398-78c71d22e86b.png)

1. Is this a specification change on Sparkle 1.13.0 (or on 1.12.0) so that I need to set appcast URL also in Info.plist, or something goes wrong on 1.13.0?
2. If I specify the appcast URL in Info.plist, can I overwrite it on SUUPdaterDelegate's `feedURLStringForUpdater: ` later?

### My spec info:

- System: OS X Version 10.11.2 (Build 15C50)
- Xcode: Xcode 7.2
- Sparkle: Sparkle 1.13.0 (via Cocoapods)
- SDK: OS X 10.11

**Comment by pornel** [comment]
Oops, the latest version instantly checks whether you have HTTPS feed URL in order to warn about lack of HTTP support.

The workaround is to set any feed URL in the plist.

**Comment by pornel** [comment]
Fixed in master

**Comment by 1024jp** [comment]
I'm grad to hear that it was not a specification change.
Thanks for fixing it and also suggesting me the workaround!

**Comment by 1024jp** [comment]
I found this issue still exists on Sparkle 1.13.1.

Is it going to be fixed later, for instance on Sparkle 1.14.0, or is there some another issue on v1.13.1?

**Comment by pornel** [comment]
:facepalm: I've tagged wrong commit. I'll try to sort out releases/tags soon.

**Comment by 1024jp** [comment]
Oh, I see. Thanks! 🐕

**Comment by gilhagi** [comment]
Hi, just to clarify, which is the final 1.13.1 tag that has this issue resolved?  "1.13.1" or "1.13.1-mistagged"?  It seems like a stupid question but the one labeled mistagged actually has commits that the 1.13.1 tag doesn't.

**Comment by pornel** [comment]
The `1.13.1-mistagged` is a mistake, and it's not the release. The current `1.31.1` tag reflects contents of the 1.13.1 release, and it has this bug.

This bug will be fixed in 1.14.0, but it's not ready yet — #753

**Comment by uranusjr** [comment]
> The current `1.31.1` tag reflects contents of the 1.13.1 release, and the 1.13.1 release has this bug.

@pornel Just to be sure, do you mean the `1.13.1` tag?

**Comment by pornel** [comment]
I mean the `1.31.1` tag has this bug. 

I hope I've fixed last issue in 1.14.0 in 9671f7f52df2425bfa922e8057e4116efb93d1da, so try that commit if you need a fixed version of Sparkle.
